### PR TITLE
Fixed relpath incorrectly trims file names which contains dot in name.

### PR DESCRIPTION
**Pull request by eMuonTau**
Hey
I modified regex that trims filenames so it can handle dots correctly.
Thanks for your awesome work.

### CODE REVIEW

**Comment by eMuonTau** [comment]
@joostlubach Can you please merge this PR? I am still having problem with Angular style file names.

**Comment by joostlubach** [comment]
Hi there, I'm so sorry I completely missed this Pull Request. Getting a lot of Github emails 😅 . I'll look at it right now.

**Comment by joostlubach** [comment]
Thank you, and apologies for my late response. I'm going to publish this now.

**Comment by eMuonTau** [comment]
No worries! I definitely understand. I was using the extension by applying the patch manually after every update :smile:. Thanks.

**Pull request merged**
